// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJO24cNe-_iRSMmoyXH67-jEOeZw_k0xk',
    appId: '1:169750653557:web:25cb520d3453abf5abe63c',
    messagingSenderId: '169750653557',
    projectId: 'my-sync-app-2025',
    authDomain: 'my-sync-app-2025.firebaseapp.com',
    storageBucket: 'my-sync-app-2025.firebasestorage.app',
    measurementId: 'G-PJZJM4XJKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22fjEnnEt1bOWxWmRC9p2cxwPEKV7R58',
    appId: '1:169750653557:android:2ea51f6769aece52abe63c',
    messagingSenderId: '169750653557',
    projectId: 'my-sync-app-2025',
    storageBucket: 'my-sync-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGo-4rZ3r9kDJKIkI7je3LfMwHV9h0yA',
    appId: '1:169750653557:ios:83f7dc1d081e0d1aabe63c',
    messagingSenderId: '169750653557',
    projectId: 'my-sync-app-2025',
    storageBucket: 'my-sync-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.tryingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSGo-4rZ3r9kDJKIkI7je3LfMwHV9h0yA',
    appId: '1:169750653557:ios:83f7dc1d081e0d1aabe63c',
    messagingSenderId: '169750653557',
    projectId: 'my-sync-app-2025',
    storageBucket: 'my-sync-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.tryingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJO24cNe-_iRSMmoyXH67-jEOeZw_k0xk',
    appId: '1:169750653557:web:3ca1ea2485a71b01abe63c',
    messagingSenderId: '169750653557',
    projectId: 'my-sync-app-2025',
    authDomain: 'my-sync-app-2025.firebaseapp.com',
    storageBucket: 'my-sync-app-2025.firebasestorage.app',
    measurementId: 'G-3EDHVGQY45',
  );

}